Models/ContactU.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChienVHShopOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactU
    {
        public int id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string content { get; set; }
    }
}

Controllers/ContactUsController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ChienVHShopOnline.Models;

namespace ChienVHShopOnline.Controllers
{
    public class ContactUsController : Controller
    {
        ChienVHShopDBEntities db = new ChienVHShopDBEntities();
        // GET: ContactUs
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ValidateCaptcha(FormCollection collection)
        {
            var respone = Request["g-recaptcha-response"];
            const string secret = "6Le2GC8UAAAAAKzGJ7VQ3kIC6zqqbcWFpbp-l6Qv";

            var client = new WebClient();
            var reply = client.DownloadString(
                        string.Format("https://www.google.com/recaptcha/api/siteverify?secret={0}&response={1}",secret,respone)
                );
            var captchaResponse = JsonConvert.DeserializeObject<CaptchaResponse>(reply);

            // Check error returns from google recaptcha
            if (!captchaResponse.Success)
            {
                // TODO: Handle error messages
                if (captchaResponse.ErrorCodes.Count <= 0) return View("Index");
                var error = captchaResponse.ErrorCodes[0].ToLower();
                switch (error)
                {
                    case "missing-input-secret":
                        ViewBag.Message = "Missing secret parameter";
                        break;
                    case "invalid-input-secret":
                        ViewBag.Message = "The secret is invalid or malformed";
                        break;
                    case "missing-input-response":
                        ViewBag.Message = "Missing response parameter";
                        break;
                    case "invalid-input-response":
                        ViewBag.Message = "The response parameter is invalid of malformed";
                        break;
                    default:
                        ViewBag.Message = "Error occured. Please try again later";
                        break;
                }
            }
            else
            {
                // TODO: Handle success case
                ContactU contact = new ContactU()
                {
                    name = collection["cusName"],
                    email = collection["cusEmail"],
                    phone = collection["cusPhone"],
                    content = collection["cusContent"]
                };
                db.ContactUs.Add(contact);
                db.SaveChanges();
                ViewBag.Message = "Your query has been submitted successfully. We will get back you you shortly!";
            }
            return View("Index");
        }
        // GET: ContactUs/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ContactUs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ContactUs/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: ContactUs/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ContactUs/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: ContactUs/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ContactUs/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/ContactUs/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layout/_MainLayout.cshtml";
}

<h2>You guys contact me if have any issues:</h2>

<p>FullName: Chien Vu Hoang</p>
<p>Email: chien.vh@gmail.com</p>
<p>Skype: chien.vh</p>
<p>Facebook: facebook.com/chienvh</p>

@if (!string.IsNullOrEmpty(ViewBag.Message))
{
    <p><b>Captcha Message: @ViewBag.Message</b></p>
}
<div class="row">
    @using (Html.BeginForm("ValidateCaptcha", "ContactUs", FormMethod.Post, new { id = "contact-form" }))
    {
        <table>
            <tr>
                <td colspan="3" style="text-align:center;"><b>Send Queries to Us</b></td>
            </tr>
            <tr>
                <td>Customer Name:</td>
                <td><input type="text" name="cusName" /></td>
            </tr>
            <tr>
                <td>Customer Phone:</td>
                <td><input type="text" name="cusPhone" /></td>
            </tr>
            <tr>
                <td>Customer Email:</td>
                <td><input type="text" name="cusEmail" /></td>
            </tr>
            <tr>
                <td>Content:</td>
                <td>
                @*<input type="text" name="cusContent" />*@
                  <textarea name="cusContent" rows="10", cols="30"></textarea>
                </td>
            </tr>
        </table>
        <div class="g-recaptcha" data-sitekey="6Le2GC8UAAAAAB8qs65dp2f5SCPs-EWOSB4HHFPz"></div>
        <br />
        <input type="submit" value="Submit Form" />
    }
</div>

<script src='https://www.google.com/recaptcha/api.js'></script>

<script type="text/javascript">
    $("#contact-form").validate({
        rules: {
            cusName: {
                required: true
            },
            cusPhone: {
                required: true
            },
            cusEmail: {
                required: true
            },
            cusContent: {
                required: true
            }
        }
    });
</script>